#!/usr/bin/env sh

echo "🔍 Verificando arquivos em busca de secrets..."

gitleaks protect --staged --verbose

if [ $? -ne 0 ]; then
    echo ""
    echo "❌ Possível secret encontrado. Commit cancelado."
    exit 1
fi

echo "✅ Nenhum secret encontrado."